### ISSUE TITLE
Google OAuth 2.0 is broken with authorization header is enabled

### ISSUE THREAD

**Issue by carlsverre** [peterhudec/authomatic#92] opened 2015-04-14 23:52 UTC
At some point today all of my OAuth 2.0 requests to Google started failing with a cryptic error:

```
[E 150414 16:23:47 __init__:333] authomatic: Google: Reported suppressed exception: FailureError('Failed to obtain OAuth 2.0 access token from https://accounts.google.com/o/oauth2/token! HTTP status: 400, message: {\n  "error" : "invalid_request",\n  "error_description" : "OAuth 2 parameters can only have a single value: client_secret"\n}.',)!
```

After a bunch of trial and error I figured out that if I disabled the authorization header while requesting a TOKEN from google it worked.  Not sure what changed but I thought I would share it here to see if other people are having the same issue.

To monkey patch Authomatic until a formal change is figured out I just did this:

```
from authomatic.providers.oauth2 import Google
setattr(Google, "_x_use_authorization_header", False)
```

**Comment by yofreke** [comment] 2015-04-15 00:36
+1

**Comment by peterhudec** [comment] 2015-04-15 08:22
Yes, I have noticed it too yesterday. It's because the client ID and secret are currently sent in the request parameters as well as in the basic authorization header of the access token request and Google probably decided that they don't like it that way. I will release a version with this issue fixed within a day.

**Comment by DavidTimms** [comment] 2015-04-15 09:20
@carlsverre Thank you for sharing that fix. I would have been completely at a loss without it.

**Comment by ivamluz** [comment] 2015-04-15 13:08
+1

**Comment by touilleMan** [comment] 2015-04-15 13:41
+1
@carlsverre big thanks for your fix ;-)

**Comment by carlsverre** [comment] 2015-04-15 13:55
@peterhudec thanks a bunch for working on a real fix.  My hack works but is a bit squirmy.  :)

Glad to help

**Comment by mr337** [comment] 2015-04-15 16:15
+1

**Comment by peterhudec** [comment] 2015-04-15 21:34
The issue is now fixed in version [0.0.13](https://pypi.python.org/pypi?:action=display&name=Authomatic&version=0.0.13).

@carlsverre thanks for the helpful quick fix. The final fix b3c9ade is a bit different however. I decided to keep the authorization headers and remove the `client_id` and `client_secret` params.

Enjoy!

**Closed by peterhudec** 2015-04-15 21:34 UTC
Labels: bug, waffle:in progress

**Comment by carlsverre** [comment] 2015-04-15 21:50
Thanks for the quick fix!  :)

**Comment by justingrayston** [comment] 2015-04-15 22:45
If you send the client id and secret as params with a get request, they show up as clear as day in the request logs. While it is only Google engineers that would see them, they still have no right to this sensitive data. Google I guess have just put a hard stop to it.

**Comment by peterhudec** [comment] 2015-04-15 22:58
@justingrayston Google still allows the consumer credentials to be sent in the request parameters **or** as the authorization header **but not both at the same time**. Actually the method of the OAuth 2.0 access token request must always by POST so the parameters are sent in the request body.

**Comment by justingrayston** [comment] 2015-04-16 05:49
+1 good to know..
